version: "3.3"

services:
  db:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    restart: always
    env_file:
      ./.env
    volumes:
      - ./.env:/wallet/usr/app/.env
  backend:
    image: wallet_backend
    env_file:
      ./.env
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./:/usr/app/wallet
    ports:
      - "8001:8001"
    depends_on:
      - db
  migration:
    image: wallet_backend
    env_file:
      ./.env
    command: ["python", "manage.py", "migrate"]
    volumes:
      - ./:/usr/app/wallet
    depends_on:
      - db
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"
  worker:
    image: wallet_backend
    command:  bash -c "rm -f -- -celerybeat && celery -A myapp worker -l INFO"
    env_file:
      ./.env
    volumes:
      - ./:/usr/app/wallet
    depends_on:
      - backend