# Generated by Django 3.2.13 on 2022-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
